//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchParsecConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwitchParsecConnection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # All configuration settings must appear on a new line.
        ///# All whitespace, besides the newline character &apos;\n&apos;, is ignored.
        ///# All settings passed via the command line take precedence.
        ///# The configuration file will be overwritten by Parsec when changing settings,
        ///#   so if you edit this file while Parsec is running, make sure to save this file
        ///#   and restart Parsec immediately so your changes are preserved.
        ///
        ///# Example:
        ///# encoder_bitrate = 10
        ///
        ///app_run_level = 3
        ///encoder_bitrate = 50
        ///encoder_vbv_max  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeParsecSettings {
            get {
                return ResourceManager.GetString("HomeParsecSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # All configuration settings must appear on a new line.
        ///# All whitespace, besides the newline character &apos;\n&apos;, is ignored.
        ///# All settings passed via the command line take precedence.
        ///# The configuration file will be overwritten by Parsec when changing settings,
        ///#   so if you edit this file while Parsec is running, make sure to save this file
        ///#   and restart Parsec immediately so your changes are preserved.
        ///
        ///# Example:
        ///# encoder_bitrate = 10
        ///
        ///app_run_level = 3
        ///encoder_bitrate = 50
        ///encoder_vbv_max  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HomeSlowerParsecSettings {
            get {
                return ResourceManager.GetString("HomeSlowerParsecSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Shadow\AppData\Roaming\Parsec\config.txt.
        /// </summary>
        internal static string ParsecConfigFile {
            get {
                return ResourceManager.GetString("ParsecConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Parsec\parsecd.exe.
        /// </summary>
        internal static string ParsecInstallLocation {
            get {
                return ResourceManager.GetString("ParsecInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # All configuration settings must appear on a new line.
        ///# All whitespace, besides the newline character &apos;\n&apos;, is ignored.
        ///# All settings passed via the command line take precedence.
        ///# The configuration file will be overwritten by Parsec when changing settings,
        ///#   so if you edit this file while Parsec is running, make sure to save this file
        ///#   and restart Parsec immediately so your changes are preserved.
        ///
        ///# Example:
        ///# encoder_bitrate = 10
        ///
        ///app_run_level = 3
        ///encoder_bitrate = 50
        ///.
        /// </summary>
        internal static string WorkParsecSettings {
            get {
                return ResourceManager.GetString("WorkParsecSettings", resourceCulture);
            }
        }
    }
}
